### ISSUE TITLE
Filter Documentation

### ISSUE THREAD

**Issue by johngroves** [ContinuumIO/intake-parquet#7]
I'm having difficulty implementing filtering through parameters in a catalog entry, are there any examples of this?

The example given uses the `open_[plugin_name]` syntax, is this the only way to pass non-string parameters?
```
from intake import open_parquet
source = open_parquet('test.parq', columns=['f', 'i32', 'cat'])
source.read().head()
```

**Comment by martindurant** [comment]
Contributions to improving the documentation, including examples, would be very well appreciated!
The general rule is, that anything that you pass to the open_parquet function should appear in the corresponding catalog entry. For your case, this would look something like
```yaml
sources:
   mysource:
      driver: parquet
      args:
         urlpath: "test.parq"
         columns: ["f",, "i22", "cat"]
```

In fact, you can get a best-guess at how to transform an open_ function call to catalog syntax by using the `.yaml()` method
```python
print(source.yaml())
```
